[project]
name = "chan_analysis"
dependencies = [
    "numpy",
    "pandas",
    "akshare",
    "Ta-lib",
]

[build-system]
requires = ["setuptools>=61.0.0,<69.3.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py312']
skip-string-normalization = true